@startuml wiki-usage

:开始;

:遇到一个问题需要查 wiki;
if (能不能在 wiki 中找到？) then (yes)
    if (文档是否失效？) then (yes)
        :找人询问、调研;
        :解决问题;
        :更新文档;
    else(no)
        :参考文档;
        :解决问题;
        :给文档赏束稻谷;
    endif
else(no)
    :找人询问、调研;
    :解决问题;
    :添加到 wiki;
endif

:结束;

@enduml
